;---------------Konstanta---------------
INPUT	EQU P0
SEVSEG	EQU P1
PILIH	EQU P2
DATA1	EQU 0
DATA2	EQU 1
DATA3	EQU 2
DATA4	EQU 3
CLEAR	EQU 0FFH

;---------------Data---------------
ANGKA:	DB 0C0H ;0
	DB 0F9H ;1
	DB 0A4H ;2
	DB 0B0H ;3
	DB 099H ;4
	DB 092H ;5
	DB 082H ;6
	DB 0F8H ;7
	DB 080H ;8
	DB 090H ;9
	DB 0FFH ;LED MATI SEMUA

;---------------Program---------------
	ORG 00H
	
	MOV DPTR,#ANGKA
	MOV DATA1,#CLEAR
	MOV DATA2,#CLEAR
	MOV DATA3,#CLEAR
	MOV DATA4,#CLEAR
	MOV R4,#CLEAR
	
IDLE:	MOV INPUT,#CLEAR
	CLR INPUT.0
	JNB INPUT.4,SATU
	JNB INPUT.5,DUA
	JNB INPUT.6,TIGA
	JNB INPUT.7,AA
	SETB INPUT.0
	CLR INPUT.1
	JNB INPUT.4,EMPAT
	JNB INPUT.5,LIMA
	JNB INPUT.6,ENAM
	JNB INPUT.7,BB
	SETB INPUT.1
	CLR INPUT.2
	JNB INPUT.4,TUJUH
	JNB INPUT.5,LAPAN
	JNB INPUT.6,SEMBIL
	JNB INPUT.7,CC
	SETB INPUT.2
	CLR INPUT.3
	JNB INPUT.4,TITIK
	JNB INPUT.5,NOL
	JNB INPUT.6,PAGER
	JNB INPUT.7,DD
	SETB INPUT.3

	LJMP IDLE
	
NOL:	MOV A, #0
	ACALL SERIAL
	LJMP IDLE
SATU:	MOV A, #1
	ACALL SERIAL
	LJMP IDLE
DUA:	MOV A, #2
	ACALL SERIAL
	LJMP IDLE
TIGA:	MOV A, #3
	ACALL SERIAL
	LJMP IDLE
EMPAT:	MOV A, #4
	ACALL SERIAL
	LJMP IDLE
LIMA:	MOV A, #5
	ACALL SERIAL
	LJMP IDLE
ENAM:	MOV A, #6
	ACALL SERIAL
	LJMP IDLE
TUJUH:	MOV A, #7
	ACALL SERIAL
	LJMP IDLE
LAPAN:	MOV A, #8
	ACALL SERIAL
	LJMP IDLE
SEMBIL:	MOV A, #9
	ACALL SERIAL
	LJMP IDLE
AA:	LJMP IDLE
BB:	LJMP IDLE
CC:	LJMP IDLE
DD:	LJMP IDLE
TITIK:	LJMP IDLE
PAGER:	LJMP IDLE

SERIAL:	MOVC A,@A+DPTR
	INC R4
	CJNE R4,#00H,FLAG1
	SJMP INPUT1
FLAG1:	CJNE R4,#01H,FLAG2
	SJMP INPUT2
FLAG2:	CJNE R4,#02H,FLAG3
	SJMP INPUT3
FLAG3:	CJNE R4,#03H,HERE
	SJMP INPUT4
	INPUT1:
		CLR PILIH.3
		MOV SEVSEG,#CLEAR
		MOV DATA1,A
		MOV SEVSEG,DATA1
		MOV PILIH,#CLEAR
		MOV SEVSEG,#CLEAR
		JMP SINI
	INPUT2:
		CLR PILIH.2
		MOV SEVSEG,#CLEAR
		MOV DATA2,A
		MOV SEVSEG,DATA2
		MOV PILIH,#CLEAR
		MOV SEVSEG,#CLEAR
		JMP SINI
	INPUT3:
		CLR PILIH.1
		MOV SEVSEG,#CLEAR
		MOV DATA3,A
		MOV SEVSEG,DATA3
		MOV PILIH,#CLEAR
		MOV SEVSEG,#CLEAR
		JMP SINI
	INPUT4:
		CLR PILIH.0
		MOV SEVSEG,#CLEAR
		MOV DATA4,A
		MOV SEVSEG,DATA4
		MOV PILIH,#CLEAR
		MOV SEVSEG,#CLEAR
		JMP SINI
	SINI:
	RET

HERE:	JMP HERE

END